### ISSUE TITLE
Alerts are not sent to slack channels

### ISSUE THREAD

**Issue by sondr3** [nais/babylon#52]

**Comment by henrikhorluck** [comment]
After pair-programming/debugging with @thokra-nav, we think it might be wise for us to change how we record our metrics, since we currently only increase the counter every time we want to send an alert, which cooperates badly with Prometheus' query-mechanics. I therefore suggest that we change it so that we instead can have a _continuous state_ that we can read a change in with Prometheus, moving some logic from Babylon to the `expr` in the alert

This was attempted fixed in https://github.com/nais/babylon/commit/3cea00be80448a348684555a27a60f6f37560ef3

It might also be wise to change it to an `gauge`, so that we can explicitly set it to 0

It might be that this `expr` also works, as credited by @thokra-nav, but we have not had time to test it yet:
```
(max_over_time(babylon_team_notifications_total[5m]) or vector(0)) - (max_over_time(babylon_team_notifications_total[5m] offset 5m) or vector(0)) > 0
```

**Comment by aasehaa** [comment]
Closed by https://github.com/nais/babylon/commit/3e5aa7b8e2a7771e06bae40dfae6dcdece26ddbd
